---
all:
  hosts:
    sonar-01:
      ansible_host: 130.193.42.106
    nexus-01:
      ansible_host: 84.252.139.72
  children:
    sonarqube:
      hosts:
        sonar-01:
    nexus:
      hosts:
        nexus-01:
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: netology